### ISSUE TITLE
ModuleNotFoundError: No module named 'SBCK.tools.__tools_cpp'

### ISSUE THREAD

**Issue by ady-br** [yrobink/SBCK#1]
Dear Robin,
I've installed your SBCK, but it turns out like this when I import the module. Please help.
`>>> import SBCK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/SBCK-master/python/SBCK/__init__.py", line 23, in <module>
    from .__QM    import QM
  File "/mnt/d/SBCK-master/python/SBCK/__QM.py", line 27, in <module>
    from .tools.__Dist import _Dist
  File "/mnt/d/SBCK-master/python/SBCK/tools/__init__.py", line 21, in <module>
    from .__tools_cpp             import SparseHist
ModuleNotFoundError: No module named 'SBCK.tools.__tools_cpp'`

**Comment by yrobink** [comment]
Dear adhybae,

I think the c++ part is not compiled, do you have installed the eigen3 c++ lib ? (https://eigen.tuxfamily.org) Can you share the output of the installation ?

Best

**Comment by adhybae** [comment]
Thanks for your response...
I have installed c++, but I'm not sure if it's properly installed.
Here's what I got after the installation:
`running install
running bdist_egg
running egg_info
writing SBCK.egg-info/PKG-INFO
writing dependency_links to SBCK.egg-info/dependency_links.txt
writing requirements to SBCK.egg-info/requires.txt
writing top-level names to SBCK.egg-info/top_level.txt
reading manifest file 'SBCK.egg-info/SOURCES.txt'
writing manifest file 'SBCK.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c /tmp/tmp0m8jc1lx.cpp -o tmp/tmp0m8jc1lx.o -std=c++14
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c /tmp/tmpijv1g3ds.cpp -o tmp/tmpijv1g3ds.o -fvisibility=hidden
building 'SBCK.tools.__tools_cpp' extension
_x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/budi/eigen/ -I/home/budi/.local/lib/python3.8/site-packages/pybind11/include -I/home/budi/.local/lib/python3.8/site-packages/pybind11/include -I/usr/include/python3.8 -c SBCK/tools/src/tools.cpp -o build/temp.linux-x86_64-3.8/SBCK/tools/src/tools.o -O3 -DVERSION_INFO="0.3.1" -std=c++14 -fvisibility=hidden
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/SBCK/tools/src/tools.o -o build/lib.linux-x86_64-3.8/SBCK/tools_/__tools_cpp.cpython-38-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/SBCK
creating build/bdist.linux-x86_64/egg/SBCK/datasets
copying build/lib.linux-x86_64-3.8/SBCK/datasets/__init__.py -> build/bdist.linux-x86_64/egg/SBCK/datasets
copying build/lib.linux-x86_64-3.8/SBCK/datasets/__multivariates.py -> build/bdist.linux-x86_64/egg/SBCK/datasets
copying build/lib.linux-x86_64-3.8/SBCK/datasets/__univariates.py -> build/bdist.linux-x86_64/egg/SBCK/datasets
creating build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__chebyshev.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__decorators.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__energy.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__entropy.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__euclidean.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__init__.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__manhattan.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__minkowski.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-3.8/SBCK/metrics/__wasserstein.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
creating build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/tools/__bin_width_estimator.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/tools/__Dist.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/tools/__init__.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/tools/__OT.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/tools/__rv_extend.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/tools/__shuffle.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/tools/__SlopeStoppingCriteria.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/tools/__tools_cpp.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-3.8/SBCK/__CDFt.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__dOTC.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__ECBC.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__init__.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__MBCn.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__MRec.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__OTC.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__QDM.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__QM.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__QMrs.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__R2D2.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-3.8/SBCK/__RBC.py -> build/bdist.linux-x86_64/egg/SBCK
byte-compiling build/bdist.linux-x86_64/egg/SBCK/datasets/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/datasets/__multivariates.py to __multivariates.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/datasets/__univariates.py to __univariates.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__chebyshev.py to __chebyshev.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__decorators.py to __decorators.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__energy.py to __energy.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__entropy.py to __entropy.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__euclidean.py to __euclidean.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__manhattan.py to __manhattan.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__minkowski.py to __minkowski.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__wasserstein.py to __wasserstein.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__bin_width_estimator.py to __bin_width_estimator.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__Dist.py to __Dist.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__OT.py to __OT.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__rv_extend.py to __rv_extend.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__shuffle.py to __shuffle.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__SlopeStoppingCriteria.py to __SlopeStoppingCriteria.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__CDFt.py to __CDFt.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__dOTC.py to __dOTC.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__ECBC.py to __ECBC.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__MBCn.py to __MBCn.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__MRec.py to __MRec.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__OTC.py to __OTC.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__QDM.py to __QDM.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__QM.py to __QM.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__QMrs.py to __QMrs.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__R2D2.py to __R2D2.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__RBC.py to __RBC.cpython-38.pyc
creating stub loader for SBCK/tools/__tools_cpp.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__tools_cpp.py to __tools_cpp.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/SBCK-0.3.1-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing SBCK-0.3.1-py3.8-linux-x86_64.egg
removing '/home/budi/.local/lib/python3.8/site-packages/SBCK-0.3.1-py3.8-linux-x86_64.egg' (and everything under it)
creating /home/budi/.local/lib/python3.8/site-packages/SBCK-0.3.1-py3.8-linux-x86_64.egg
Extracting SBCK-0.3.1-py3.8-linux-x86_64.egg to /home/budi/.local/lib/python3.8/site-packages
SBCK 0.3.1 is already the active version in easy-install.pth

Installed /home/budi/.local/lib/python3.8/site-packages/SBCK-0.3.1-py3.8-linux-x86_64.egg
Processing dependencies for SBCK==0.3.1
Searching for pybind11==2.6.2
Best match: pybind11 2.6.2
Adding pybind11 2.6.2 to easy-install.pth file
Installing pybind11-config script to /home/budi/.local/bin

Using /usr/local/lib/python3.8/dist-packages`

**Comment by ady-br** [comment]
Dear @yrobink 
I've managed to install this SBCK after creating a new conda env. I'm not sure where the problem is. But it's installed successfully in a new conda env. Thanks for your help. 
Regards.
![sbck](https://user-images.githubusercontent.com/26314707/113473260-bbb0e300-9492-11eb-8ef9-1c8052264048.jpg)

**Comment by fangwangwf** [comment]
Dear @ady-br,
I have the same issue. Could you specify (step by step) how you installed the SBCK under a conda virtual environment? Thank you very much!

I used the command line: python3 setup.py install --user eigen="path-to-eigen" to install the SBCK, but the SBCK package is install under .local instead of the .conda virtual environment. 

Thank you!

**Comment by yrobink** [comment]
Dear @fangwangwf ,
If you are in conda virtual env the command 
~~~shell
python3 setup.py install
~~~
should work. The `--user` option is used when the python installation is the root installation.  For the `eigen` option, use it only if the Eigen library is not found, i.e. if Eigen is installed in a non-standard path. For example, if Eigen is installed on `/opt/Eigen`, you should use a command like:
~~~shell
python3 setup.py install eigen=/opt/Eigen
~~~

Best

**Comment by fangwangwf** [comment]
Dear @yrobink,

Thank you very much for your detailed information and it works perfectly!
